import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import ContextWrapper from "./contxtWrapper";
import { PrimaryButton } from "@/components/common/button/primary-button";

const roboto = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ContextWrapper>{children}</ContextWrapper>
      </body>
    </html>
  );
}
